version: "3.7"

services:
  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - 5432:5432 
    env_file:
      - .env
  app:
    depends_on: 
      - db
    container_name: app
    image: uzpayment:latest
    tty: true
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - ./:/app
    ports:
      - 1598:8080
    env_file:
      - .env