version: "3.7"

services:
  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: tempuser
      POSTGRES_PASSWORD: temppw
      POSTGRES_DB: tempdb
    ports:
      - 5432:5432 
    volumes:
      - database:/var/lib/postgresql/data
  app:
    depends_on: 
      - db
    container_name: app
    tty: true
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - ./:/app
    ports:
      - 1598:8080
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_NAME: tempdb
      DATABASE_USER: tempuser
      DATABASE_PASSWORD: temppw

volumes:
    database:
      driver: local